package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DbmailFiltersId generated by hbm2java
 */
@Embeddable
public class DbmailFiltersId implements java.io.Serializable {

	private long userId;
	private long id;

	public DbmailFiltersId() {
	}

	public DbmailFiltersId(long userId, long id) {
		this.userId = userId;
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "id", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbmailFiltersId))
			return false;
		DbmailFiltersId castOther = (DbmailFiltersId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getId() == castOther.getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getId();
		return result;
	}

}
