package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.Size;

/**
 * DbmailAuthlogId generated by hbm2java
 */
@Embeddable
public class DbmailAuthlogId implements java.io.Serializable {

	private Long id;
	private String userid;
	private String service;
	private Date loginTime;
	private Date logoutTime;
	private String srcIp;
	private Long srcPort;
	private String dstIp;
	private Long dstPort;
	private String status;
	private long bytesRx;
	private long bytesTx;

	public DbmailAuthlogId() {
	}

	public DbmailAuthlogId(long bytesRx, long bytesTx) {
		this.bytesRx = bytesRx;
		this.bytesTx = bytesTx;
	}
	public DbmailAuthlogId(Long id, String userid, String service,
			Date loginTime, Date logoutTime, String srcIp, Long srcPort,
			String dstIp, Long dstPort, String status, long bytesRx,
			long bytesTx) {
		this.id = id;
		this.userid = userid;
		this.service = service;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
		this.srcIp = srcIp;
		this.srcPort = srcPort;
		this.dstIp = dstIp;
		this.dstPort = dstPort;
		this.status = status;
		this.bytesRx = bytesRx;
		this.bytesTx = bytesTx;
	}

	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "userid", length = 100)
	@Size(max = 100)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "service", length = 32)
	@Size(max = 32)
	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	@Column(name = "login_time", length = 29)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Column(name = "logout_time", length = 29)
	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

	@Column(name = "src_ip", length = 16)
	@Size(max = 16)
	public String getSrcIp() {
		return this.srcIp;
	}

	public void setSrcIp(String srcIp) {
		this.srcIp = srcIp;
	}

	@Column(name = "src_port")
	public Long getSrcPort() {
		return this.srcPort;
	}

	public void setSrcPort(Long srcPort) {
		this.srcPort = srcPort;
	}

	@Column(name = "dst_ip", length = 16)
	@Size(max = 16)
	public String getDstIp() {
		return this.dstIp;
	}

	public void setDstIp(String dstIp) {
		this.dstIp = dstIp;
	}

	@Column(name = "dst_port")
	public Long getDstPort() {
		return this.dstPort;
	}

	public void setDstPort(Long dstPort) {
		this.dstPort = dstPort;
	}

	@Column(name = "status", length = 32)
	@Size(max = 32)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "bytes_rx", nullable = false)
	public long getBytesRx() {
		return this.bytesRx;
	}

	public void setBytesRx(long bytesRx) {
		this.bytesRx = bytesRx;
	}

	@Column(name = "bytes_tx", nullable = false)
	public long getBytesTx() {
		return this.bytesTx;
	}

	public void setBytesTx(long bytesTx) {
		this.bytesTx = bytesTx;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbmailAuthlogId))
			return false;
		DbmailAuthlogId castOther = (DbmailAuthlogId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getUserid() == castOther.getUserid()) || (this
						.getUserid() != null
						&& castOther.getUserid() != null && this.getUserid()
						.equals(castOther.getUserid())))
				&& ((this.getService() == castOther.getService()) || (this
						.getService() != null
						&& castOther.getService() != null && this.getService()
						.equals(castOther.getService())))
				&& ((this.getLoginTime() == castOther.getLoginTime()) || (this
						.getLoginTime() != null
						&& castOther.getLoginTime() != null && this
						.getLoginTime().equals(castOther.getLoginTime())))
				&& ((this.getLogoutTime() == castOther.getLogoutTime()) || (this
						.getLogoutTime() != null
						&& castOther.getLogoutTime() != null && this
						.getLogoutTime().equals(castOther.getLogoutTime())))
				&& ((this.getSrcIp() == castOther.getSrcIp()) || (this
						.getSrcIp() != null
						&& castOther.getSrcIp() != null && this.getSrcIp()
						.equals(castOther.getSrcIp())))
				&& ((this.getSrcPort() == castOther.getSrcPort()) || (this
						.getSrcPort() != null
						&& castOther.getSrcPort() != null && this.getSrcPort()
						.equals(castOther.getSrcPort())))
				&& ((this.getDstIp() == castOther.getDstIp()) || (this
						.getDstIp() != null
						&& castOther.getDstIp() != null && this.getDstIp()
						.equals(castOther.getDstIp())))
				&& ((this.getDstPort() == castOther.getDstPort()) || (this
						.getDstPort() != null
						&& castOther.getDstPort() != null && this.getDstPort()
						.equals(castOther.getDstPort())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus()
						.equals(castOther.getStatus())))
				&& (this.getBytesRx() == castOther.getBytesRx())
				&& (this.getBytesTx() == castOther.getBytesTx());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getUserid() == null ? 0 : this.getUserid().hashCode());
		result = 37 * result
				+ (getService() == null ? 0 : this.getService().hashCode());
		result = 37 * result
				+ (getLoginTime() == null ? 0 : this.getLoginTime().hashCode());
		result = 37
				* result
				+ (getLogoutTime() == null ? 0 : this.getLogoutTime()
						.hashCode());
		result = 37 * result
				+ (getSrcIp() == null ? 0 : this.getSrcIp().hashCode());
		result = 37 * result
				+ (getSrcPort() == null ? 0 : this.getSrcPort().hashCode());
		result = 37 * result
				+ (getDstIp() == null ? 0 : this.getDstIp().hashCode());
		result = 37 * result
				+ (getDstPort() == null ? 0 : this.getDstPort().hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (int) this.getBytesRx();
		result = 37 * result + (int) this.getBytesTx();
		return result;
	}

}
