package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * DbmailKeywords generated by hbm2java
 */
@Entity
@Table(name = "dbmail_keywords", schema = "public")
public class DbmailKeywords implements java.io.Serializable {

	private DbmailKeywordsId id;
	private DbmailMessages dbmailMessages;

	public DbmailKeywords() {
	}

	public DbmailKeywords(DbmailKeywordsId id, DbmailMessages dbmailMessages) {
		this.id = id;
		this.dbmailMessages = dbmailMessages;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "messageIdnr", column = @Column(name = "message_idnr", nullable = false)),
			@AttributeOverride(name = "keyword", column = @Column(name = "keyword", nullable = false, length = 64))})
	@NotNull
	public DbmailKeywordsId getId() {
		return this.id;
	}

	public void setId(DbmailKeywordsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "message_idnr", nullable = false, insertable = false, updatable = false)
	@NotNull
	public DbmailMessages getDbmailMessages() {
		return this.dbmailMessages;
	}

	public void setDbmailMessages(DbmailMessages dbmailMessages) {
		this.dbmailMessages = dbmailMessages;
	}

}
