package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * DbmailMessages generated by hbm2java
 */
@Entity
@Table(name = "dbmail_messages", schema = "public")
public class DbmailMessages implements java.io.Serializable {

	private long messageIdnr;
	private DbmailMailboxes dbmailMailboxes;
	private DbmailPhysmessage dbmailPhysmessage;
	private short seenFlag;
	private short answeredFlag;
	private short deletedFlag;
	private short flaggedFlag;
	private short recentFlag;
	private short draftFlag;
	private String uniqueId;
	private short status;
	private Set<DbmailKeywords> dbmailKeywordses = new HashSet<DbmailKeywords>(
			0);

	public DbmailMessages() {
	}

	public DbmailMessages(long messageIdnr, short seenFlag, short answeredFlag,
			short deletedFlag, short flaggedFlag, short recentFlag,
			short draftFlag, String uniqueId, short status) {
		this.messageIdnr = messageIdnr;
		this.seenFlag = seenFlag;
		this.answeredFlag = answeredFlag;
		this.deletedFlag = deletedFlag;
		this.flaggedFlag = flaggedFlag;
		this.recentFlag = recentFlag;
		this.draftFlag = draftFlag;
		this.uniqueId = uniqueId;
		this.status = status;
	}
	public DbmailMessages(long messageIdnr, DbmailMailboxes dbmailMailboxes,
			DbmailPhysmessage dbmailPhysmessage, short seenFlag,
			short answeredFlag, short deletedFlag, short flaggedFlag,
			short recentFlag, short draftFlag, String uniqueId, short status,
			Set<DbmailKeywords> dbmailKeywordses) {
		this.messageIdnr = messageIdnr;
		this.dbmailMailboxes = dbmailMailboxes;
		this.dbmailPhysmessage = dbmailPhysmessage;
		this.seenFlag = seenFlag;
		this.answeredFlag = answeredFlag;
		this.deletedFlag = deletedFlag;
		this.flaggedFlag = flaggedFlag;
		this.recentFlag = recentFlag;
		this.draftFlag = draftFlag;
		this.uniqueId = uniqueId;
		this.status = status;
		this.dbmailKeywordses = dbmailKeywordses;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "message_idnr", unique = true, nullable = false)
	public long getMessageIdnr() {
		return this.messageIdnr;
	}

	public void setMessageIdnr(long messageIdnr) {
		this.messageIdnr = messageIdnr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mailbox_idnr")
	public DbmailMailboxes getDbmailMailboxes() {
		return this.dbmailMailboxes;
	}

	public void setDbmailMailboxes(DbmailMailboxes dbmailMailboxes) {
		this.dbmailMailboxes = dbmailMailboxes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "physmessage_id")
	public DbmailPhysmessage getDbmailPhysmessage() {
		return this.dbmailPhysmessage;
	}

	public void setDbmailPhysmessage(DbmailPhysmessage dbmailPhysmessage) {
		this.dbmailPhysmessage = dbmailPhysmessage;
	}

	@Column(name = "seen_flag", nullable = false)
	public short getSeenFlag() {
		return this.seenFlag;
	}

	public void setSeenFlag(short seenFlag) {
		this.seenFlag = seenFlag;
	}

	@Column(name = "answered_flag", nullable = false)
	public short getAnsweredFlag() {
		return this.answeredFlag;
	}

	public void setAnsweredFlag(short answeredFlag) {
		this.answeredFlag = answeredFlag;
	}

	@Column(name = "deleted_flag", nullable = false)
	public short getDeletedFlag() {
		return this.deletedFlag;
	}

	public void setDeletedFlag(short deletedFlag) {
		this.deletedFlag = deletedFlag;
	}

	@Column(name = "flagged_flag", nullable = false)
	public short getFlaggedFlag() {
		return this.flaggedFlag;
	}

	public void setFlaggedFlag(short flaggedFlag) {
		this.flaggedFlag = flaggedFlag;
	}

	@Column(name = "recent_flag", nullable = false)
	public short getRecentFlag() {
		return this.recentFlag;
	}

	public void setRecentFlag(short recentFlag) {
		this.recentFlag = recentFlag;
	}

	@Column(name = "draft_flag", nullable = false)
	public short getDraftFlag() {
		return this.draftFlag;
	}

	public void setDraftFlag(short draftFlag) {
		this.draftFlag = draftFlag;
	}

	@Column(name = "unique_id", nullable = false, length = 70)
	@NotNull
	@Size(max = 70)
	public String getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	@Column(name = "status", nullable = false)
	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dbmailMessages")
	public Set<DbmailKeywords> getDbmailKeywordses() {
		return this.dbmailKeywordses;
	}

	public void setDbmailKeywordses(Set<DbmailKeywords> dbmailKeywordses) {
		this.dbmailKeywordses = dbmailKeywordses;
	}

}
