package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DbmailSubjectfieldId generated by hbm2java
 */
@Embeddable
public class DbmailSubjectfieldId implements java.io.Serializable {

	private Long physmessageId;
	private String subjectfield;

	public DbmailSubjectfieldId() {
	}

	public DbmailSubjectfieldId(Long physmessageId, String subjectfield) {
		this.physmessageId = physmessageId;
		this.subjectfield = subjectfield;
	}

	@Column(name = "physmessage_id")
	public Long getPhysmessageId() {
		return this.physmessageId;
	}

	public void setPhysmessageId(Long physmessageId) {
		this.physmessageId = physmessageId;
	}

	@Column(name = "subjectfield")
	public String getSubjectfield() {
		return this.subjectfield;
	}

	public void setSubjectfield(String subjectfield) {
		this.subjectfield = subjectfield;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbmailSubjectfieldId))
			return false;
		DbmailSubjectfieldId castOther = (DbmailSubjectfieldId) other;

		return ((this.getPhysmessageId() == castOther.getPhysmessageId()) || (this
				.getPhysmessageId() != null
				&& castOther.getPhysmessageId() != null && this
				.getPhysmessageId().equals(castOther.getPhysmessageId())))
				&& ((this.getSubjectfield() == castOther.getSubjectfield()) || (this
						.getSubjectfield() != null
						&& castOther.getSubjectfield() != null && this
						.getSubjectfield().equals(castOther.getSubjectfield())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPhysmessageId() == null ? 0 : this.getPhysmessageId()
						.hashCode());
		result = 37
				* result
				+ (getSubjectfield() == null ? 0 : this.getSubjectfield()
						.hashCode());
		return result;
	}

}
