package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DbmailSubscriptionId generated by hbm2java
 */
@Embeddable
public class DbmailSubscriptionId implements java.io.Serializable {

	private long userId;
	private long mailboxId;

	public DbmailSubscriptionId() {
	}

	public DbmailSubscriptionId(long userId, long mailboxId) {
		this.userId = userId;
		this.mailboxId = mailboxId;
	}

	@Column(name = "user_id", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "mailbox_id", nullable = false)
	public long getMailboxId() {
		return this.mailboxId;
	}

	public void setMailboxId(long mailboxId) {
		this.mailboxId = mailboxId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbmailSubscriptionId))
			return false;
		DbmailSubscriptionId castOther = (DbmailSubscriptionId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getMailboxId() == castOther.getMailboxId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getMailboxId();
		return result;
	}

}
