package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * DbmailSubscription generated by hbm2java
 */
@Entity
@Table(name = "dbmail_subscription", schema = "public")
public class DbmailSubscription implements java.io.Serializable {

	private DbmailSubscriptionId id;
	private DbmailMailboxes dbmailMailboxes;
	private DbmailUsers dbmailUsers;

	public DbmailSubscription() {
	}

	public DbmailSubscription(DbmailSubscriptionId id,
			DbmailMailboxes dbmailMailboxes, DbmailUsers dbmailUsers) {
		this.id = id;
		this.dbmailMailboxes = dbmailMailboxes;
		this.dbmailUsers = dbmailUsers;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "mailboxId", column = @Column(name = "mailbox_id", nullable = false))})
	@NotNull
	public DbmailSubscriptionId getId() {
		return this.id;
	}

	public void setId(DbmailSubscriptionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mailbox_id", nullable = false, insertable = false, updatable = false)
	@NotNull
	public DbmailMailboxes getDbmailMailboxes() {
		return this.dbmailMailboxes;
	}

	public void setDbmailMailboxes(DbmailMailboxes dbmailMailboxes) {
		this.dbmailMailboxes = dbmailMailboxes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	@NotNull
	public DbmailUsers getDbmailUsers() {
		return this.dbmailUsers;
	}

	public void setDbmailUsers(DbmailUsers dbmailUsers) {
		this.dbmailUsers = dbmailUsers;
	}

}
