package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DbmailHeaderId generated by hbm2java
 */
@Embeddable
public class DbmailHeaderId implements java.io.Serializable {

	private long physmessageId;
	private long headernameId;
	private long headervalueId;

	public DbmailHeaderId() {
	}

	public DbmailHeaderId(long physmessageId, long headernameId,
			long headervalueId) {
		this.physmessageId = physmessageId;
		this.headernameId = headernameId;
		this.headervalueId = headervalueId;
	}

	@Column(name = "physmessage_id", nullable = false)
	public long getPhysmessageId() {
		return this.physmessageId;
	}

	public void setPhysmessageId(long physmessageId) {
		this.physmessageId = physmessageId;
	}

	@Column(name = "headername_id", nullable = false)
	public long getHeadernameId() {
		return this.headernameId;
	}

	public void setHeadernameId(long headernameId) {
		this.headernameId = headernameId;
	}

	@Column(name = "headervalue_id", nullable = false)
	public long getHeadervalueId() {
		return this.headervalueId;
	}

	public void setHeadervalueId(long headervalueId) {
		this.headervalueId = headervalueId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbmailHeaderId))
			return false;
		DbmailHeaderId castOther = (DbmailHeaderId) other;

		return (this.getPhysmessageId() == castOther.getPhysmessageId())
				&& (this.getHeadernameId() == castOther.getHeadernameId())
				&& (this.getHeadervalueId() == castOther.getHeadervalueId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPhysmessageId();
		result = 37 * result + (int) this.getHeadernameId();
		result = 37 * result + (int) this.getHeadervalueId();
		return result;
	}

}
