package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

/**
 * DbmailEnvelope generated by hbm2java
 */
@Entity
@Table(name = "dbmail_envelope", schema = "public", uniqueConstraints = {
		@UniqueConstraint(columnNames = "physmessage_id"),
		@UniqueConstraint(columnNames = {"physmessage_id", "id"})})
public class DbmailEnvelope implements java.io.Serializable {

	private long id;
	private DbmailPhysmessage dbmailPhysmessage;
	private String envelope;

	public DbmailEnvelope() {
	}

	public DbmailEnvelope(long id, DbmailPhysmessage dbmailPhysmessage,
			String envelope) {
		this.id = id;
		this.dbmailPhysmessage = dbmailPhysmessage;
		this.envelope = envelope;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "physmessage_id", unique = true, nullable = false)
	@NotNull
	public DbmailPhysmessage getDbmailPhysmessage() {
		return this.dbmailPhysmessage;
	}

	public void setDbmailPhysmessage(DbmailPhysmessage dbmailPhysmessage) {
		this.dbmailPhysmessage = dbmailPhysmessage;
	}

	@Column(name = "envelope", nullable = false)
	@NotNull
	public String getEnvelope() {
		return this.envelope;
	}

	public void setEnvelope(String envelope) {
		this.envelope = envelope;
	}

}
