package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * DbmailAliases generated by hbm2java
 */
@Entity
@Table(name = "dbmail_aliases", schema = "public")
@DiscriminatorColumn(name="aliasType",discriminatorType=DiscriminatorType.CHAR)
@DiscriminatorValue("D")
@Inheritance(strategy=InheritanceType.JOINED)

public class DbmailAliases implements java.io.Serializable {

	private long aliasIdnr;
	private String alias;
	private String deliverTo;
	private long clientIdnr;
	private String aliasType;
	
	public DbmailAliases() {
	}

	public DbmailAliases(long aliasIdnr, String alias, String deliverTo,
			long clientIdnr) {
		this.aliasIdnr = aliasIdnr;
		this.alias = alias;
		this.deliverTo = deliverTo;
		this.clientIdnr = clientIdnr;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "alias_idnr", unique = true, nullable = false)
	public long getAliasIdnr() {
		return this.aliasIdnr;
	}

	public void setAliasIdnr(long aliasIdnr) {
		this.aliasIdnr = aliasIdnr;
	}

	@Column(name = "alias", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "deliver_to", nullable = false, length = 250)
	@NotNull
	@Size(max = 250)
	public String getDeliverTo() {
		return this.deliverTo;
	}

	public void setDeliverTo(String deliverTo) {
		this.deliverTo = deliverTo;
	}

	@Column(name = "client_idnr", nullable = false)
	public long getClientIdnr() {
		return this.clientIdnr;
	}

	public void setClientIdnr(long clientIdnr) {
		this.clientIdnr = clientIdnr;
	}

	public String getAliasType() {
		return aliasType;
	}

	public void setAliasType(String aliasType) {
		this.aliasType = aliasType;
	}

}
