package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * DbmailMimeparts generated by hbm2java
 */
@Entity
@Table(name = "dbmail_mimeparts", schema = "public")
public class DbmailMimeparts implements java.io.Serializable {

	private long id;
	private String hash;
	private byte[] data;
	private long size;
	private Set<DbmailPartlists> dbmailPartlistses = new HashSet<DbmailPartlists>(
			0);

	public DbmailMimeparts() {
	}

	public DbmailMimeparts(long id, String hash, byte[] data, long size) {
		this.id = id;
		this.hash = hash;
		this.data = data;
		this.size = size;
	}
	public DbmailMimeparts(long id, String hash, byte[] data, long size,
			Set<DbmailPartlists> dbmailPartlistses) {
		this.id = id;
		this.hash = hash;
		this.data = data;
		this.size = size;
		this.dbmailPartlistses = dbmailPartlistses;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "hash", nullable = false, length = 256)
	@NotNull
	@Size(max = 256)
	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	@Column(name = "data", nullable = false)
	@NotNull
	public byte[] getData() {
		return this.data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

	@Column(name = "size", nullable = false)
	public long getSize() {
		return this.size;
	}

	public void setSize(long size) {
		this.size = size;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dbmailMimeparts")
	public Set<DbmailPartlists> getDbmailPartlistses() {
		return this.dbmailPartlistses;
	}

	public void setDbmailPartlistses(Set<DbmailPartlists> dbmailPartlistses) {
		this.dbmailPartlistses = dbmailPartlistses;
	}

}
