package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DbmailTofieldId generated by hbm2java
 */
@Embeddable
public class DbmailTofieldId implements java.io.Serializable {

	private Long physmessageId;
	private String tofield;

	public DbmailTofieldId() {
	}

	public DbmailTofieldId(Long physmessageId, String tofield) {
		this.physmessageId = physmessageId;
		this.tofield = tofield;
	}

	@Column(name = "physmessage_id")
	public Long getPhysmessageId() {
		return this.physmessageId;
	}

	public void setPhysmessageId(Long physmessageId) {
		this.physmessageId = physmessageId;
	}

	@Column(name = "tofield")
	public String getTofield() {
		return this.tofield;
	}

	public void setTofield(String tofield) {
		this.tofield = tofield;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbmailTofieldId))
			return false;
		DbmailTofieldId castOther = (DbmailTofieldId) other;

		return ((this.getPhysmessageId() == castOther.getPhysmessageId()) || (this
				.getPhysmessageId() != null
				&& castOther.getPhysmessageId() != null && this
				.getPhysmessageId().equals(castOther.getPhysmessageId())))
				&& ((this.getTofield() == castOther.getTofield()) || (this
						.getTofield() != null
						&& castOther.getTofield() != null && this.getTofield()
						.equals(castOther.getTofield())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPhysmessageId() == null ? 0 : this.getPhysmessageId()
						.hashCode());
		result = 37 * result
				+ (getTofield() == null ? 0 : this.getTofield().hashCode());
		return result;
	}

}
