package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DbmailSubjectfield generated by hbm2java
 */
@Entity
@Table(name = "dbmail_subjectfield", schema = "public")
public class DbmailSubjectfield implements java.io.Serializable {

	private DbmailSubjectfieldId id;

	public DbmailSubjectfield() {
	}

	public DbmailSubjectfield(DbmailSubjectfieldId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "physmessageId", column = @Column(name = "physmessage_id")),
			@AttributeOverride(name = "subjectfield", column = @Column(name = "subjectfield"))})
	public DbmailSubjectfieldId getId() {
		return this.id;
	}

	public void setId(DbmailSubjectfieldId id) {
		this.id = id;
	}

}
