package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * DbmailUsermapId generated by hbm2java
 */
@Embeddable
public class DbmailUsermapId implements java.io.Serializable {

	private String login;
	private String sockAllow;
	private String sockDeny;
	private String userid;

	public DbmailUsermapId() {
	}

	public DbmailUsermapId(String login, String sockAllow, String sockDeny,
			String userid) {
		this.login = login;
		this.sockAllow = sockAllow;
		this.sockDeny = sockDeny;
		this.userid = userid;
	}

	@Column(name = "login", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "sock_allow", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getSockAllow() {
		return this.sockAllow;
	}

	public void setSockAllow(String sockAllow) {
		this.sockAllow = sockAllow;
	}

	@Column(name = "sock_deny", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getSockDeny() {
		return this.sockDeny;
	}

	public void setSockDeny(String sockDeny) {
		this.sockDeny = sockDeny;
	}

	@Column(name = "userid", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbmailUsermapId))
			return false;
		DbmailUsermapId castOther = (DbmailUsermapId) other;

		return ((this.getLogin() == castOther.getLogin()) || (this.getLogin() != null
				&& castOther.getLogin() != null && this.getLogin().equals(
				castOther.getLogin())))
				&& ((this.getSockAllow() == castOther.getSockAllow()) || (this
						.getSockAllow() != null
						&& castOther.getSockAllow() != null && this
						.getSockAllow().equals(castOther.getSockAllow())))
				&& ((this.getSockDeny() == castOther.getSockDeny()) || (this
						.getSockDeny() != null
						&& castOther.getSockDeny() != null && this
						.getSockDeny().equals(castOther.getSockDeny())))
				&& ((this.getUserid() == castOther.getUserid()) || (this
						.getUserid() != null
						&& castOther.getUserid() != null && this.getUserid()
						.equals(castOther.getUserid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLogin() == null ? 0 : this.getLogin().hashCode());
		result = 37 * result
				+ (getSockAllow() == null ? 0 : this.getSockAllow().hashCode());
		result = 37 * result
				+ (getSockDeny() == null ? 0 : this.getSockDeny().hashCode());
		result = 37 * result
				+ (getUserid() == null ? 0 : this.getUserid().hashCode());
		return result;
	}

}
