package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * DbmailAcl generated by hbm2java
 */
@Entity
@Table(name = "dbmail_acl", schema = "public")
public class DbmailAcl implements java.io.Serializable {

	private DbmailAclId id;
	private DbmailMailboxes dbmailMailboxes;
	private DbmailUsers dbmailUsers;
	private short lookupFlag;
	private short readFlag;
	private short seenFlag;
	private short writeFlag;
	private short insertFlag;
	private short postFlag;
	private short createFlag;
	private short deleteFlag;
	private short deletedFlag;
	private short expungeFlag;
	private short administerFlag;

	public DbmailAcl() {
	}

	public DbmailAcl(DbmailAclId id, DbmailMailboxes dbmailMailboxes,
			DbmailUsers dbmailUsers, short lookupFlag, short readFlag,
			short seenFlag, short writeFlag, short insertFlag, short postFlag,
			short createFlag, short deleteFlag, short deletedFlag,
			short expungeFlag, short administerFlag) {
		this.id = id;
		this.dbmailMailboxes = dbmailMailboxes;
		this.dbmailUsers = dbmailUsers;
		this.lookupFlag = lookupFlag;
		this.readFlag = readFlag;
		this.seenFlag = seenFlag;
		this.writeFlag = writeFlag;
		this.insertFlag = insertFlag;
		this.postFlag = postFlag;
		this.createFlag = createFlag;
		this.deleteFlag = deleteFlag;
		this.deletedFlag = deletedFlag;
		this.expungeFlag = expungeFlag;
		this.administerFlag = administerFlag;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "mailboxId", column = @Column(name = "mailbox_id", nullable = false))})
	@NotNull
	public DbmailAclId getId() {
		return this.id;
	}

	public void setId(DbmailAclId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mailbox_id", nullable = false, insertable = false, updatable = false)
	@NotNull
	public DbmailMailboxes getDbmailMailboxes() {
		return this.dbmailMailboxes;
	}

	public void setDbmailMailboxes(DbmailMailboxes dbmailMailboxes) {
		this.dbmailMailboxes = dbmailMailboxes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	@NotNull
	public DbmailUsers getDbmailUsers() {
		return this.dbmailUsers;
	}

	public void setDbmailUsers(DbmailUsers dbmailUsers) {
		this.dbmailUsers = dbmailUsers;
	}

	@Column(name = "lookup_flag", nullable = false)
	public short getLookupFlag() {
		return this.lookupFlag;
	}

	public void setLookupFlag(short lookupFlag) {
		this.lookupFlag = lookupFlag;
	}

	@Column(name = "read_flag", nullable = false)
	public short getReadFlag() {
		return this.readFlag;
	}

	public void setReadFlag(short readFlag) {
		this.readFlag = readFlag;
	}

	@Column(name = "seen_flag", nullable = false)
	public short getSeenFlag() {
		return this.seenFlag;
	}

	public void setSeenFlag(short seenFlag) {
		this.seenFlag = seenFlag;
	}

	@Column(name = "write_flag", nullable = false)
	public short getWriteFlag() {
		return this.writeFlag;
	}

	public void setWriteFlag(short writeFlag) {
		this.writeFlag = writeFlag;
	}

	@Column(name = "insert_flag", nullable = false)
	public short getInsertFlag() {
		return this.insertFlag;
	}

	public void setInsertFlag(short insertFlag) {
		this.insertFlag = insertFlag;
	}

	@Column(name = "post_flag", nullable = false)
	public short getPostFlag() {
		return this.postFlag;
	}

	public void setPostFlag(short postFlag) {
		this.postFlag = postFlag;
	}

	@Column(name = "create_flag", nullable = false)
	public short getCreateFlag() {
		return this.createFlag;
	}

	public void setCreateFlag(short createFlag) {
		this.createFlag = createFlag;
	}

	@Column(name = "delete_flag", nullable = false)
	public short getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(short deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Column(name = "deleted_flag", nullable = false)
	public short getDeletedFlag() {
		return this.deletedFlag;
	}

	public void setDeletedFlag(short deletedFlag) {
		this.deletedFlag = deletedFlag;
	}

	@Column(name = "expunge_flag", nullable = false)
	public short getExpungeFlag() {
		return this.expungeFlag;
	}

	public void setExpungeFlag(short expungeFlag) {
		this.expungeFlag = expungeFlag;
	}

	@Column(name = "administer_flag", nullable = false)
	public short getAdministerFlag() {
		return this.administerFlag;
	}

	public void setAdministerFlag(short administerFlag) {
		this.administerFlag = administerFlag;
	}

}
