package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DbmailTofield generated by hbm2java
 */
@Entity
@Table(name = "dbmail_tofield", schema = "public")
public class DbmailTofield implements java.io.Serializable {

	private DbmailTofieldId id;

	public DbmailTofield() {
	}

	public DbmailTofield(DbmailTofieldId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "physmessageId", column = @Column(name = "physmessage_id")),
			@AttributeOverride(name = "tofield", column = @Column(name = "tofield"))})
	public DbmailTofieldId getId() {
		return this.id;
	}

	public void setId(DbmailTofieldId id) {
		this.id = id;
	}

}
