package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * DbmailUsers generated by hbm2java
 */
@Entity
@Table(name = "dbmail_users", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "userid"))
@DiscriminatorColumn(name="userType",discriminatorType=DiscriminatorType.CHAR)
@DiscriminatorValue("D")
@Inheritance(strategy=InheritanceType.JOINED)

public class DbmailUsers implements java.io.Serializable {

	private long userIdnr;
	private String userid;
	private String passwd;
	private long clientIdnr;
	private long maxmailSize;
	private long curmailSize;
	private long maxsieveSize;
	private long cursieveSize;
	private String encryptionType;
	private Date lastLogin;
	private String userType;
	private DbmailAutoReplies dbmailAutoReplies;
	private Set<DbmailMailboxes> dbmailMailboxeses = new HashSet<DbmailMailboxes>(
			0);
	private Set<DbmailSievescripts> dbmailSievescriptses = new HashSet<DbmailSievescripts>(
			0);
	private Set<DbmailFilters> dbmailFilterses = new HashSet<DbmailFilters>(0);
	private DbmailAutoNotifications dbmailAutoNotifications;
	private Set<DbmailSubscription> dbmailSubscriptions = new HashSet<DbmailSubscription>(
			0);
	private Set<DbmailAcl> dbmailAcls = new HashSet<DbmailAcl>(0);

	public DbmailUsers() {
	}

	public DbmailUsers(long userIdnr, String userid, String passwd,
			long clientIdnr, long maxmailSize, long curmailSize,
			long maxsieveSize, long cursieveSize, String encryptionType,
			Date lastLogin) {
		this.userIdnr = userIdnr;
		this.userid = userid;
		this.passwd = passwd;
		this.clientIdnr = clientIdnr;
		this.maxmailSize = maxmailSize;
		this.curmailSize = curmailSize;
		this.maxsieveSize = maxsieveSize;
		this.cursieveSize = cursieveSize;
		this.encryptionType = encryptionType;
		this.lastLogin = lastLogin;
	}
	public DbmailUsers(long userIdnr, String userid, String passwd,
			long clientIdnr, long maxmailSize, long curmailSize,
			long maxsieveSize, long cursieveSize, String encryptionType,
			Date lastLogin, DbmailAutoReplies dbmailAutoReplies,
			Set<DbmailMailboxes> dbmailMailboxeses,
			Set<DbmailSievescripts> dbmailSievescriptses,
			Set<DbmailFilters> dbmailFilterses,
			DbmailAutoNotifications dbmailAutoNotifications,
			Set<DbmailSubscription> dbmailSubscriptions,
			Set<DbmailAcl> dbmailAcls) {
		this.userIdnr = userIdnr;
		this.userid = userid;
		this.passwd = passwd;
		this.clientIdnr = clientIdnr;
		this.maxmailSize = maxmailSize;
		this.curmailSize = curmailSize;
		this.maxsieveSize = maxsieveSize;
		this.cursieveSize = cursieveSize;
		this.encryptionType = encryptionType;
		this.lastLogin = lastLogin;
		this.dbmailAutoReplies = dbmailAutoReplies;
		this.dbmailMailboxeses = dbmailMailboxeses;
		this.dbmailSievescriptses = dbmailSievescriptses;
		this.dbmailFilterses = dbmailFilterses;
		this.dbmailAutoNotifications = dbmailAutoNotifications;
		this.dbmailSubscriptions = dbmailSubscriptions;
		this.dbmailAcls = dbmailAcls;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "user_idnr", unique = true, nullable = false)
	public long getUserIdnr() {
		return this.userIdnr;
	}

	public void setUserIdnr(long userIdnr) {
		this.userIdnr = userIdnr;
	}

	@Column(name = "userid", unique = true, nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "passwd", nullable = false, length = 130)
	@NotNull
	@Size(max = 130)
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	@Column(name = "client_idnr", nullable = false)
	public long getClientIdnr() {
		return this.clientIdnr;
	}

	public void setClientIdnr(long clientIdnr) {
		this.clientIdnr = clientIdnr;
	}

	@Column(name = "maxmail_size", nullable = false)
	public long getMaxmailSize() {
		return this.maxmailSize;
	}

	public void setMaxmailSize(long maxmailSize) {
		this.maxmailSize = maxmailSize;
	}

	@Column(name = "curmail_size", nullable = false)
	public long getCurmailSize() {
		return this.curmailSize;
	}

	public void setCurmailSize(long curmailSize) {
		this.curmailSize = curmailSize;
	}

	@Column(name = "maxsieve_size", nullable = false)
	public long getMaxsieveSize() {
		return this.maxsieveSize;
	}

	public void setMaxsieveSize(long maxsieveSize) {
		this.maxsieveSize = maxsieveSize;
	}

	@Column(name = "cursieve_size", nullable = false)
	public long getCursieveSize() {
		return this.cursieveSize;
	}

	public void setCursieveSize(long cursieveSize) {
		this.cursieveSize = cursieveSize;
	}

	@Column(name = "encryption_type", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getEncryptionType() {
		return this.encryptionType;
	}

	public void setEncryptionType(String encryptionType) {
		this.encryptionType = encryptionType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_login", nullable = false, length = 29)
	@NotNull
	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "dbmailUsers")
	public DbmailAutoReplies getDbmailAutoReplies() {
		return this.dbmailAutoReplies;
	}

	public void setDbmailAutoReplies(DbmailAutoReplies dbmailAutoReplies) {
		this.dbmailAutoReplies = dbmailAutoReplies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dbmailUsers")
	public Set<DbmailMailboxes> getDbmailMailboxeses() {
		return this.dbmailMailboxeses;
	}

	public void setDbmailMailboxeses(Set<DbmailMailboxes> dbmailMailboxeses) {
		this.dbmailMailboxeses = dbmailMailboxeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dbmailUsers")
	public Set<DbmailSievescripts> getDbmailSievescriptses() {
		return this.dbmailSievescriptses;
	}

	public void setDbmailSievescriptses(
			Set<DbmailSievescripts> dbmailSievescriptses) {
		this.dbmailSievescriptses = dbmailSievescriptses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dbmailUsers")
	public Set<DbmailFilters> getDbmailFilterses() {
		return this.dbmailFilterses;
	}

	public void setDbmailFilterses(Set<DbmailFilters> dbmailFilterses) {
		this.dbmailFilterses = dbmailFilterses;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "dbmailUsers")
	public DbmailAutoNotifications getDbmailAutoNotifications() {
		return this.dbmailAutoNotifications;
	}

	public void setDbmailAutoNotifications(
			DbmailAutoNotifications dbmailAutoNotifications) {
		this.dbmailAutoNotifications = dbmailAutoNotifications;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dbmailUsers")
	public Set<DbmailSubscription> getDbmailSubscriptions() {
		return this.dbmailSubscriptions;
	}

	public void setDbmailSubscriptions(
			Set<DbmailSubscription> dbmailSubscriptions) {
		this.dbmailSubscriptions = dbmailSubscriptions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dbmailUsers")
	public Set<DbmailAcl> getDbmailAcls() {
		return this.dbmailAcls;
	}

	public void setDbmailAcls(Set<DbmailAcl> dbmailAcls) {
		this.dbmailAcls = dbmailAcls;
	}

	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

}
