package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * DbmailAuthlog generated by hbm2java
 */
@Entity
@Table(name = "dbmail_authlog", schema = "public")
public class DbmailAuthlog implements java.io.Serializable {

	private DbmailAuthlogId id;

	public DbmailAuthlog() {
	}

	public DbmailAuthlog(DbmailAuthlogId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "userid", column = @Column(name = "userid", length = 100)),
			@AttributeOverride(name = "service", column = @Column(name = "service", length = 32)),
			@AttributeOverride(name = "loginTime", column = @Column(name = "login_time", length = 29)),
			@AttributeOverride(name = "logoutTime", column = @Column(name = "logout_time", length = 29)),
			@AttributeOverride(name = "srcIp", column = @Column(name = "src_ip", length = 16)),
			@AttributeOverride(name = "srcPort", column = @Column(name = "src_port")),
			@AttributeOverride(name = "dstIp", column = @Column(name = "dst_ip", length = 16)),
			@AttributeOverride(name = "dstPort", column = @Column(name = "dst_port")),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 32)),
			@AttributeOverride(name = "bytesRx", column = @Column(name = "bytes_rx", nullable = false)),
			@AttributeOverride(name = "bytesTx", column = @Column(name = "bytes_tx", nullable = false))})
	@NotNull
	public DbmailAuthlogId getId() {
		return this.id;
	}

	public void setId(DbmailAuthlogId id) {
		this.id = id;
	}

}
