package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DbmailCcfield generated by hbm2java
 */
@Entity
@Table(name = "dbmail_ccfield", schema = "public")
public class DbmailCcfield implements java.io.Serializable {

	private DbmailCcfieldId id;

	public DbmailCcfield() {
	}

	public DbmailCcfield(DbmailCcfieldId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "physmessageId", column = @Column(name = "physmessage_id")),
			@AttributeOverride(name = "ccfield", column = @Column(name = "ccfield"))})
	public DbmailCcfieldId getId() {
		return this.id;
	}

	public void setId(DbmailCcfieldId id) {
		this.id = id;
	}

}
