package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * DbmailKeywordsId generated by hbm2java
 */
@Embeddable
public class DbmailKeywordsId implements java.io.Serializable {

	private long messageIdnr;
	private String keyword;

	public DbmailKeywordsId() {
	}

	public DbmailKeywordsId(long messageIdnr, String keyword) {
		this.messageIdnr = messageIdnr;
		this.keyword = keyword;
	}

	@Column(name = "message_idnr", nullable = false)
	public long getMessageIdnr() {
		return this.messageIdnr;
	}

	public void setMessageIdnr(long messageIdnr) {
		this.messageIdnr = messageIdnr;
	}

	@Column(name = "keyword", nullable = false, length = 64)
	@NotNull
	@Size(max = 64)
	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbmailKeywordsId))
			return false;
		DbmailKeywordsId castOther = (DbmailKeywordsId) other;

		return (this.getMessageIdnr() == castOther.getMessageIdnr())
				&& ((this.getKeyword() == castOther.getKeyword()) || (this
						.getKeyword() != null
						&& castOther.getKeyword() != null && this.getKeyword()
						.equals(castOther.getKeyword())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMessageIdnr();
		result = 37 * result
				+ (getKeyword() == null ? 0 : this.getKeyword().hashCode());
		return result;
	}

}
