package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DbmailCcfieldId generated by hbm2java
 */
@Embeddable
public class DbmailCcfieldId implements java.io.Serializable {

	private Long physmessageId;
	private String ccfield;

	public DbmailCcfieldId() {
	}

	public DbmailCcfieldId(Long physmessageId, String ccfield) {
		this.physmessageId = physmessageId;
		this.ccfield = ccfield;
	}

	@Column(name = "physmessage_id")
	public Long getPhysmessageId() {
		return this.physmessageId;
	}

	public void setPhysmessageId(Long physmessageId) {
		this.physmessageId = physmessageId;
	}

	@Column(name = "ccfield")
	public String getCcfield() {
		return this.ccfield;
	}

	public void setCcfield(String ccfield) {
		this.ccfield = ccfield;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbmailCcfieldId))
			return false;
		DbmailCcfieldId castOther = (DbmailCcfieldId) other;

		return ((this.getPhysmessageId() == castOther.getPhysmessageId()) || (this
				.getPhysmessageId() != null
				&& castOther.getPhysmessageId() != null && this
				.getPhysmessageId().equals(castOther.getPhysmessageId())))
				&& ((this.getCcfield() == castOther.getCcfield()) || (this
						.getCcfield() != null
						&& castOther.getCcfield() != null && this.getCcfield()
						.equals(castOther.getCcfield())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPhysmessageId() == null ? 0 : this.getPhysmessageId()
						.hashCode());
		result = 37 * result
				+ (getCcfield() == null ? 0 : this.getCcfield().hashCode());
		return result;
	}

}
