package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

/**
 * DbmailUsermap generated by hbm2java
 */
@Entity
@Table(name = "dbmail_usermap", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"login", "sock_allow", "userid"}))
public class DbmailUsermap implements java.io.Serializable {

	private DbmailUsermapId id;

	public DbmailUsermap() {
	}

	public DbmailUsermap(DbmailUsermapId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "login", column = @Column(name = "login", nullable = false, length = 100)),
			@AttributeOverride(name = "sockAllow", column = @Column(name = "sock_allow", nullable = false, length = 100)),
			@AttributeOverride(name = "sockDeny", column = @Column(name = "sock_deny", nullable = false, length = 100)),
			@AttributeOverride(name = "userid", column = @Column(name = "userid", nullable = false, length = 100))})
	@NotNull
	public DbmailUsermapId getId() {
		return this.id;
	}

	public void setId(DbmailUsermapId id) {
		this.id = id;
	}

}
