package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DbmailFromfield generated by hbm2java
 */
@Entity
@Table(name = "dbmail_fromfield", schema = "public")
public class DbmailFromfield implements java.io.Serializable {

	private DbmailFromfieldId id;

	public DbmailFromfield() {
	}

	public DbmailFromfield(DbmailFromfieldId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "physmessageId", column = @Column(name = "physmessage_id")),
			@AttributeOverride(name = "fromfield", column = @Column(name = "fromfield"))})
	public DbmailFromfieldId getId() {
		return this.id;
	}

	public void setId(DbmailFromfieldId id) {
		this.id = id;
	}

}
