package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DbmailPhysmessage generated by hbm2java
 */
@Entity
@Table(name = "dbmail_physmessage", schema = "public")
public class DbmailPhysmessage implements java.io.Serializable {

	private long id;
	private long messagesize;
	private long rfcsize;
	private Date internalDate;
	private Set<DbmailHeader> dbmailHeaders = new HashSet<DbmailHeader>(0);
	private Set<DbmailMessages> dbmailMessageses = new HashSet<DbmailMessages>(
			0);
	private Set<DbmailPartlists> dbmailPartlistses = new HashSet<DbmailPartlists>(
			0);
	private Set<DbmailMessageblks> dbmailMessageblkses = new HashSet<DbmailMessageblks>(
			0);
	private Set<DbmailEnvelope> dbmailEnvelopes = new HashSet<DbmailEnvelope>(0);
	private Set<DbmailReferencesfield> dbmailReferencesfields = new HashSet<DbmailReferencesfield>(
			0);

	public DbmailPhysmessage() {
	}

	public DbmailPhysmessage(long id, long messagesize, long rfcsize) {
		this.id = id;
		this.messagesize = messagesize;
		this.rfcsize = rfcsize;
	}
	public DbmailPhysmessage(long id, long messagesize, long rfcsize,
			Date internalDate, Set<DbmailHeader> dbmailHeaders,
			Set<DbmailMessages> dbmailMessageses,
			Set<DbmailPartlists> dbmailPartlistses,
			Set<DbmailMessageblks> dbmailMessageblkses,
			Set<DbmailEnvelope> dbmailEnvelopes,
			Set<DbmailReferencesfield> dbmailReferencesfields) {
		this.id = id;
		this.messagesize = messagesize;
		this.rfcsize = rfcsize;
		this.internalDate = internalDate;
		this.dbmailHeaders = dbmailHeaders;
		this.dbmailMessageses = dbmailMessageses;
		this.dbmailPartlistses = dbmailPartlistses;
		this.dbmailMessageblkses = dbmailMessageblkses;
		this.dbmailEnvelopes = dbmailEnvelopes;
		this.dbmailReferencesfields = dbmailReferencesfields;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "messagesize", nullable = false)
	public long getMessagesize() {
		return this.messagesize;
	}

	public void setMessagesize(long messagesize) {
		this.messagesize = messagesize;
	}

	@Column(name = "rfcsize", nullable = false)
	public long getRfcsize() {
		return this.rfcsize;
	}

	public void setRfcsize(long rfcsize) {
		this.rfcsize = rfcsize;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "internal_date", length = 29)
	public Date getInternalDate() {
		return this.internalDate;
	}

	public void setInternalDate(Date internalDate) {
		this.internalDate = internalDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dbmailPhysmessage")
	public Set<DbmailHeader> getDbmailHeaders() {
		return this.dbmailHeaders;
	}

	public void setDbmailHeaders(Set<DbmailHeader> dbmailHeaders) {
		this.dbmailHeaders = dbmailHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dbmailPhysmessage")
	public Set<DbmailMessages> getDbmailMessageses() {
		return this.dbmailMessageses;
	}

	public void setDbmailMessageses(Set<DbmailMessages> dbmailMessageses) {
		this.dbmailMessageses = dbmailMessageses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dbmailPhysmessage")
	public Set<DbmailPartlists> getDbmailPartlistses() {
		return this.dbmailPartlistses;
	}

	public void setDbmailPartlistses(Set<DbmailPartlists> dbmailPartlistses) {
		this.dbmailPartlistses = dbmailPartlistses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dbmailPhysmessage")
	public Set<DbmailMessageblks> getDbmailMessageblkses() {
		return this.dbmailMessageblkses;
	}

	public void setDbmailMessageblkses(
			Set<DbmailMessageblks> dbmailMessageblkses) {
		this.dbmailMessageblkses = dbmailMessageblkses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dbmailPhysmessage")
	public Set<DbmailEnvelope> getDbmailEnvelopes() {
		return this.dbmailEnvelopes;
	}

	public void setDbmailEnvelopes(Set<DbmailEnvelope> dbmailEnvelopes) {
		this.dbmailEnvelopes = dbmailEnvelopes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dbmailPhysmessage")
	public Set<DbmailReferencesfield> getDbmailReferencesfields() {
		return this.dbmailReferencesfields;
	}

	public void setDbmailReferencesfields(
			Set<DbmailReferencesfield> dbmailReferencesfields) {
		this.dbmailReferencesfields = dbmailReferencesfields;
	}

}
