package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DbmailFromfieldId generated by hbm2java
 */
@Embeddable
public class DbmailFromfieldId implements java.io.Serializable {

	private Long physmessageId;
	private String fromfield;

	public DbmailFromfieldId() {
	}

	public DbmailFromfieldId(Long physmessageId, String fromfield) {
		this.physmessageId = physmessageId;
		this.fromfield = fromfield;
	}

	@Column(name = "physmessage_id")
	public Long getPhysmessageId() {
		return this.physmessageId;
	}

	public void setPhysmessageId(Long physmessageId) {
		this.physmessageId = physmessageId;
	}

	@Column(name = "fromfield")
	public String getFromfield() {
		return this.fromfield;
	}

	public void setFromfield(String fromfield) {
		this.fromfield = fromfield;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbmailFromfieldId))
			return false;
		DbmailFromfieldId castOther = (DbmailFromfieldId) other;

		return ((this.getPhysmessageId() == castOther.getPhysmessageId()) || (this
				.getPhysmessageId() != null
				&& castOther.getPhysmessageId() != null && this
				.getPhysmessageId().equals(castOther.getPhysmessageId())))
				&& ((this.getFromfield() == castOther.getFromfield()) || (this
						.getFromfield() != null
						&& castOther.getFromfield() != null && this
						.getFromfield().equals(castOther.getFromfield())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPhysmessageId() == null ? 0 : this.getPhysmessageId()
						.hashCode());
		result = 37 * result
				+ (getFromfield() == null ? 0 : this.getFromfield().hashCode());
		return result;
	}

}
