package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DbmailPartlistsId generated by hbm2java
 */
@Embeddable
public class DbmailPartlistsId implements java.io.Serializable {

	private long physmessageId;
	private short isHeader;
	private int partKey;
	private int partDepth;
	private int partOrder;
	private long partId;

	public DbmailPartlistsId() {
	}

	public DbmailPartlistsId(long physmessageId, short isHeader, int partKey,
			int partDepth, int partOrder, long partId) {
		this.physmessageId = physmessageId;
		this.isHeader = isHeader;
		this.partKey = partKey;
		this.partDepth = partDepth;
		this.partOrder = partOrder;
		this.partId = partId;
	}

	@Column(name = "physmessage_id", nullable = false)
	public long getPhysmessageId() {
		return this.physmessageId;
	}

	public void setPhysmessageId(long physmessageId) {
		this.physmessageId = physmessageId;
	}

	@Column(name = "is_header", nullable = false)
	public short getIsHeader() {
		return this.isHeader;
	}

	public void setIsHeader(short isHeader) {
		this.isHeader = isHeader;
	}

	@Column(name = "part_key", nullable = false)
	public int getPartKey() {
		return this.partKey;
	}

	public void setPartKey(int partKey) {
		this.partKey = partKey;
	}

	@Column(name = "part_depth", nullable = false)
	public int getPartDepth() {
		return this.partDepth;
	}

	public void setPartDepth(int partDepth) {
		this.partDepth = partDepth;
	}

	@Column(name = "part_order", nullable = false)
	public int getPartOrder() {
		return this.partOrder;
	}

	public void setPartOrder(int partOrder) {
		this.partOrder = partOrder;
	}

	@Column(name = "part_id", nullable = false)
	public long getPartId() {
		return this.partId;
	}

	public void setPartId(long partId) {
		this.partId = partId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbmailPartlistsId))
			return false;
		DbmailPartlistsId castOther = (DbmailPartlistsId) other;

		return (this.getPhysmessageId() == castOther.getPhysmessageId())
				&& (this.getIsHeader() == castOther.getIsHeader())
				&& (this.getPartKey() == castOther.getPartKey())
				&& (this.getPartDepth() == castOther.getPartDepth())
				&& (this.getPartOrder() == castOther.getPartOrder())
				&& (this.getPartId() == castOther.getPartId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPhysmessageId();
		result = 37 * result + this.getIsHeader();
		result = 37 * result + this.getPartKey();
		result = 37 * result + this.getPartDepth();
		result = 37 * result + this.getPartOrder();
		result = 37 * result + (int) this.getPartId();
		return result;
	}

}
