package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * DbmailMessageblks generated by hbm2java
 */
@Entity
@Table(name = "dbmail_messageblks", schema = "public")
public class DbmailMessageblks implements java.io.Serializable {

	private long messageblkIdnr;
	private DbmailPhysmessage dbmailPhysmessage;
	private byte[] messageblk;
	private long blocksize;
	private short isHeader;

	public DbmailMessageblks() {
	}

	public DbmailMessageblks(long messageblkIdnr, byte[] messageblk,
			long blocksize, short isHeader) {
		this.messageblkIdnr = messageblkIdnr;
		this.messageblk = messageblk;
		this.blocksize = blocksize;
		this.isHeader = isHeader;
	}
	public DbmailMessageblks(long messageblkIdnr,
			DbmailPhysmessage dbmailPhysmessage, byte[] messageblk,
			long blocksize, short isHeader) {
		this.messageblkIdnr = messageblkIdnr;
		this.dbmailPhysmessage = dbmailPhysmessage;
		this.messageblk = messageblk;
		this.blocksize = blocksize;
		this.isHeader = isHeader;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "messageblk_idnr", unique = true, nullable = false)
	public long getMessageblkIdnr() {
		return this.messageblkIdnr;
	}

	public void setMessageblkIdnr(long messageblkIdnr) {
		this.messageblkIdnr = messageblkIdnr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "physmessage_id")
	public DbmailPhysmessage getDbmailPhysmessage() {
		return this.dbmailPhysmessage;
	}

	public void setDbmailPhysmessage(DbmailPhysmessage dbmailPhysmessage) {
		this.dbmailPhysmessage = dbmailPhysmessage;
	}

	@Column(name = "messageblk", nullable = false)
	@NotNull
	public byte[] getMessageblk() {
		return this.messageblk;
	}

	public void setMessageblk(byte[] messageblk) {
		this.messageblk = messageblk;
	}

	@Column(name = "blocksize", nullable = false)
	public long getBlocksize() {
		return this.blocksize;
	}

	public void setBlocksize(long blocksize) {
		this.blocksize = blocksize;
	}

	@Column(name = "is_header", nullable = false)
	public short getIsHeader() {
		return this.isHeader;
	}

	public void setIsHeader(short isHeader) {
		this.isHeader = isHeader;
	}

}
