package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

/**
 * DbmailPbsp generated by hbm2java
 */
@Entity
@Table(name = "dbmail_pbsp", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "ipnumber"))
public class DbmailPbsp implements java.io.Serializable {

	private long idnr;
	private Date since;
	private Serializable ipnumber;

	public DbmailPbsp() {
	}

	public DbmailPbsp(long idnr, Date since, Serializable ipnumber) {
		this.idnr = idnr;
		this.since = since;
		this.ipnumber = ipnumber;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idnr", unique = true, nullable = false)
	public long getIdnr() {
		return this.idnr;
	}

	public void setIdnr(long idnr) {
		this.idnr = idnr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "since", nullable = false, length = 29)
	@NotNull
	public Date getSince() {
		return this.since;
	}

	public void setSince(Date since) {
		this.since = since;
	}

	@Column(name = "ipnumber", unique = true, nullable = false)
	@NotNull
	public Serializable getIpnumber() {
		return this.ipnumber;
	}

	public void setIpnumber(Serializable ipnumber) {
		this.ipnumber = ipnumber;
	}

}
