package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DbmailAutoNotifications generated by hbm2java
 */
@Entity
@Table(name = "dbmail_auto_notifications", schema = "public")
public class DbmailAutoNotifications implements java.io.Serializable {

	private long userIdnr;
	private DbmailUsers dbmailUsers;
	private String notifyAddress;

	public DbmailAutoNotifications() {
	}

	public DbmailAutoNotifications(DbmailUsers dbmailUsers) {
		this.dbmailUsers = dbmailUsers;
	}
	public DbmailAutoNotifications(DbmailUsers dbmailUsers, String notifyAddress) {
		this.dbmailUsers = dbmailUsers;
		this.notifyAddress = notifyAddress;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "dbmailUsers"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "user_idnr", unique = true, nullable = false)
	public long getUserIdnr() {
		return this.userIdnr;
	}

	public void setUserIdnr(long userIdnr) {
		this.userIdnr = userIdnr;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@NotNull
	public DbmailUsers getDbmailUsers() {
		return this.dbmailUsers;
	}

	public void setDbmailUsers(DbmailUsers dbmailUsers) {
		this.dbmailUsers = dbmailUsers;
	}

	@Column(name = "notify_address", length = 100)
	@Size(max = 100)
	public String getNotifyAddress() {
		return this.notifyAddress;
	}

	public void setNotifyAddress(String notifyAddress) {
		this.notifyAddress = notifyAddress;
	}

}
