package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

/**
 * DbmailReferencesfield generated by hbm2java
 */
@Entity
@Table(name = "dbmail_referencesfield", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"physmessage_id", "referencesfield"}))
public class DbmailReferencesfield implements java.io.Serializable {

	private long id;
	private DbmailPhysmessage dbmailPhysmessage;
	private String referencesfield;

	public DbmailReferencesfield() {
	}

	public DbmailReferencesfield(long id, DbmailPhysmessage dbmailPhysmessage,
			String referencesfield) {
		this.id = id;
		this.dbmailPhysmessage = dbmailPhysmessage;
		this.referencesfield = referencesfield;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "physmessage_id", nullable = false)
	@NotNull
	public DbmailPhysmessage getDbmailPhysmessage() {
		return this.dbmailPhysmessage;
	}

	public void setDbmailPhysmessage(DbmailPhysmessage dbmailPhysmessage) {
		this.dbmailPhysmessage = dbmailPhysmessage;
	}

	@Column(name = "referencesfield", nullable = false)
	@NotNull
	public String getReferencesfield() {
		return this.referencesfield;
	}

	public void setReferencesfield(String referencesfield) {
		this.referencesfield = referencesfield;
	}

}
