package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

/**
 * DbmailReplycache generated by hbm2java
 */
@Entity
@Table(name = "dbmail_replycache", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"to_addr", "from_addr", "handle"}))
public class DbmailReplycache implements java.io.Serializable {

	private DbmailReplycacheId id;

	public DbmailReplycache() {
	}

	public DbmailReplycache(DbmailReplycacheId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "toAddr", column = @Column(name = "to_addr", nullable = false, length = 100)),
			@AttributeOverride(name = "fromAddr", column = @Column(name = "from_addr", nullable = false, length = 100)),
			@AttributeOverride(name = "handle", column = @Column(name = "handle", length = 100)),
			@AttributeOverride(name = "lastseen", column = @Column(name = "lastseen", nullable = false, length = 29))})
	@NotNull
	public DbmailReplycacheId getId() {
		return this.id;
	}

	public void setId(DbmailReplycacheId id) {
		this.id = id;
	}

}
