package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * DbmailSievescripts generated by hbm2java
 */
@Entity
@Table(name = "dbmail_sievescripts", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"owner_idnr", "name"}))
public class DbmailSievescripts implements java.io.Serializable {

	private long id;
	private DbmailUsers dbmailUsers;
	private short active;
	private String name;
	private String script;

	public DbmailSievescripts() {
	}

	public DbmailSievescripts(long id, DbmailUsers dbmailUsers, short active,
			String name, String script) {
		this.id = id;
		this.dbmailUsers = dbmailUsers;
		this.active = active;
		this.name = name;
		this.script = script;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner_idnr", nullable = false)
	@NotNull
	public DbmailUsers getDbmailUsers() {
		return this.dbmailUsers;
	}

	public void setDbmailUsers(DbmailUsers dbmailUsers) {
		this.dbmailUsers = dbmailUsers;
	}

	@Column(name = "active", nullable = false)
	public short getActive() {
		return this.active;
	}

	public void setActive(short active) {
		this.active = active;
	}

	@Column(name = "name", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "script", nullable = false)
	@NotNull
	public String getScript() {
		return this.script;
	}

	public void setScript(String script) {
		this.script = script;
	}

}
