package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * DbmailHeadername generated by hbm2java
 */
@Entity
@Table(name = "dbmail_headername", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "headername"))
public class DbmailHeadername implements java.io.Serializable {

	private long id;
	private String headername;
	private Set<DbmailHeader> dbmailHeaders = new HashSet<DbmailHeader>(0);

	public DbmailHeadername() {
	}

	public DbmailHeadername(long id, String headername) {
		this.id = id;
		this.headername = headername;
	}
	public DbmailHeadername(long id, String headername,
			Set<DbmailHeader> dbmailHeaders) {
		this.id = id;
		this.headername = headername;
		this.dbmailHeaders = dbmailHeaders;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "headername", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getHeadername() {
		return this.headername;
	}

	public void setHeadername(String headername) {
		this.headername = headername;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dbmailHeadername")
	public Set<DbmailHeader> getDbmailHeaders() {
		return this.dbmailHeaders;
	}

	public void setDbmailHeaders(Set<DbmailHeader> dbmailHeaders) {
		this.dbmailHeaders = dbmailHeaders;
	}

	@Override
	public String toString() {
		return headername;
	}

}
