package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * DbmailFilters generated by hbm2java
 */
@Entity
@Table(name = "dbmail_filters", schema = "public")
public class DbmailFilters implements java.io.Serializable {

	private DbmailFiltersId id;
	private DbmailUsers dbmailUsers;
	private String headername;
	private String headervalue;
	private String mailbox;

	public DbmailFilters() {
	}

	public DbmailFilters(DbmailFiltersId id, DbmailUsers dbmailUsers,
			String headername, String headervalue, String mailbox) {
		this.id = id;
		this.dbmailUsers = dbmailUsers;
		this.headername = headername;
		this.headervalue = headervalue;
		this.mailbox = mailbox;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false))})
	@NotNull
	public DbmailFiltersId getId() {
		return this.id;
	}

	public void setId(DbmailFiltersId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	@NotNull
	public DbmailUsers getDbmailUsers() {
		return this.dbmailUsers;
	}

	public void setDbmailUsers(DbmailUsers dbmailUsers) {
		this.dbmailUsers = dbmailUsers;
	}

	@Column(name = "headername", nullable = false, length = 128)
	@NotNull
	@Size(max = 128)
	public String getHeadername() {
		return this.headername;
	}

	public void setHeadername(String headername) {
		this.headername = headername;
	}

	@Column(name = "headervalue", nullable = false)
	@NotNull
	public String getHeadervalue() {
		return this.headervalue;
	}

	public void setHeadervalue(String headervalue) {
		this.headervalue = headervalue;
	}

	@Column(name = "mailbox", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getMailbox() {
		return this.mailbox;
	}

	public void setMailbox(String mailbox) {
		this.mailbox = mailbox;
	}

}
