package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DbmailAutoReplies generated by hbm2java
 */
@Entity
@Table(name = "dbmail_auto_replies", schema = "public")
public class DbmailAutoReplies implements java.io.Serializable {

	private long userIdnr;
	private DbmailUsers dbmailUsers;
	private Date startDate;
	private Date stopDate;
	private String replyBody;

	public DbmailAutoReplies() {
	}

	public DbmailAutoReplies(DbmailUsers dbmailUsers, Date startDate,
			Date stopDate) {
		this.dbmailUsers = dbmailUsers;
		this.startDate = startDate;
		this.stopDate = stopDate;
	}
	public DbmailAutoReplies(DbmailUsers dbmailUsers, Date startDate,
			Date stopDate, String replyBody) {
		this.dbmailUsers = dbmailUsers;
		this.startDate = startDate;
		this.stopDate = stopDate;
		this.replyBody = replyBody;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "dbmailUsers"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "user_idnr", unique = true, nullable = false)
	public long getUserIdnr() {
		return this.userIdnr;
	}

	public void setUserIdnr(long userIdnr) {
		this.userIdnr = userIdnr;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@NotNull
	public DbmailUsers getDbmailUsers() {
		return this.dbmailUsers;
	}

	public void setDbmailUsers(DbmailUsers dbmailUsers) {
		this.dbmailUsers = dbmailUsers;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", nullable = false, length = 29)
	@NotNull
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "stop_date", nullable = false, length = 29)
	@NotNull
	public Date getStopDate() {
		return this.stopDate;
	}

	public void setStopDate(Date stopDate) {
		this.stopDate = stopDate;
	}

	@Column(name = "reply_body")
	public String getReplyBody() {
		return this.replyBody;
	}

	public void setReplyBody(String replyBody) {
		this.replyBody = replyBody;
	}

}
