package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DbmailDatefield generated by hbm2java
 */
@Entity
@Table(name = "dbmail_datefield", schema = "public")
public class DbmailDatefield implements java.io.Serializable {

	private DbmailDatefieldId id;

	public DbmailDatefield() {
	}

	public DbmailDatefield(DbmailDatefieldId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "physmessageId", column = @Column(name = "physmessage_id")),
			@AttributeOverride(name = "datefield", column = @Column(name = "datefield", length = 29)),
			@AttributeOverride(name = "sortfield", column = @Column(name = "sortfield"))})
	public DbmailDatefieldId getId() {
		return this.id;
	}

	public void setId(DbmailDatefieldId id) {
		this.id = id;
	}

}
