package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * DbmailHeadervalue generated by hbm2java
 */
@Entity
@Table(name = "dbmail_headervalue", schema = "public")
public class DbmailHeadervalue implements java.io.Serializable {

	private long id;
	private String hash;
	private String headervalue;
	private String sortfield;
	private Date datefield;
	private Set<DbmailHeader> dbmailHeaders = new HashSet<DbmailHeader>(0);

	public DbmailHeadervalue() {
	}

	public DbmailHeadervalue(long id, String hash, String headervalue) {
		this.id = id;
		this.hash = hash;
		this.headervalue = headervalue;
	}
	public DbmailHeadervalue(long id, String hash, String headervalue,
			String sortfield, Date datefield, Set<DbmailHeader> dbmailHeaders) {
		this.id = id;
		this.hash = hash;
		this.headervalue = headervalue;
		this.sortfield = sortfield;
		this.datefield = datefield;
		this.dbmailHeaders = dbmailHeaders;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "hash", nullable = false, length = 256)
	@NotNull
	@Size(max = 256)
	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	@Column(name = "headervalue", nullable = false)
	@NotNull
	public String getHeadervalue() {
		return this.headervalue;
	}

	public void setHeadervalue(String headervalue) {
		this.headervalue = headervalue;
	}

	@Column(name = "sortfield")
	public String getSortfield() {
		return this.sortfield;
	}

	public void setSortfield(String sortfield) {
		this.sortfield = sortfield;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datefield", length = 29)
	public Date getDatefield() {
		return this.datefield;
	}

	public void setDatefield(Date datefield) {
		this.datefield = datefield;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dbmailHeadervalue")
	public Set<DbmailHeader> getDbmailHeaders() {
		return this.dbmailHeaders;
	}

	public void setDbmailHeaders(Set<DbmailHeader> dbmailHeaders) {
		this.dbmailHeaders = dbmailHeaders;
	}

	@Override
	public String toString() {
		return headervalue;
	}

}
