package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * DbmailReplycacheId generated by hbm2java
 */
@Embeddable
public class DbmailReplycacheId implements java.io.Serializable {

	private String toAddr;
	private String fromAddr;
	private String handle;
	private Date lastseen;

	public DbmailReplycacheId() {
	}

	public DbmailReplycacheId(String toAddr, String fromAddr, Date lastseen) {
		this.toAddr = toAddr;
		this.fromAddr = fromAddr;
		this.lastseen = lastseen;
	}
	public DbmailReplycacheId(String toAddr, String fromAddr, String handle,
			Date lastseen) {
		this.toAddr = toAddr;
		this.fromAddr = fromAddr;
		this.handle = handle;
		this.lastseen = lastseen;
	}

	@Column(name = "to_addr", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getToAddr() {
		return this.toAddr;
	}

	public void setToAddr(String toAddr) {
		this.toAddr = toAddr;
	}

	@Column(name = "from_addr", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getFromAddr() {
		return this.fromAddr;
	}

	public void setFromAddr(String fromAddr) {
		this.fromAddr = fromAddr;
	}

	@Column(name = "handle", length = 100)
	@Size(max = 100)
	public String getHandle() {
		return this.handle;
	}

	public void setHandle(String handle) {
		this.handle = handle;
	}

	@Column(name = "lastseen", nullable = false, length = 29)
	@NotNull
	public Date getLastseen() {
		return this.lastseen;
	}

	public void setLastseen(Date lastseen) {
		this.lastseen = lastseen;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbmailReplycacheId))
			return false;
		DbmailReplycacheId castOther = (DbmailReplycacheId) other;

		return ((this.getToAddr() == castOther.getToAddr()) || (this
				.getToAddr() != null
				&& castOther.getToAddr() != null && this.getToAddr().equals(
				castOther.getToAddr())))
				&& ((this.getFromAddr() == castOther.getFromAddr()) || (this
						.getFromAddr() != null
						&& castOther.getFromAddr() != null && this
						.getFromAddr().equals(castOther.getFromAddr())))
				&& ((this.getHandle() == castOther.getHandle()) || (this
						.getHandle() != null
						&& castOther.getHandle() != null && this.getHandle()
						.equals(castOther.getHandle())))
				&& ((this.getLastseen() == castOther.getLastseen()) || (this
						.getLastseen() != null
						&& castOther.getLastseen() != null && this
						.getLastseen().equals(castOther.getLastseen())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getToAddr() == null ? 0 : this.getToAddr().hashCode());
		result = 37 * result
				+ (getFromAddr() == null ? 0 : this.getFromAddr().hashCode());
		result = 37 * result
				+ (getHandle() == null ? 0 : this.getHandle().hashCode());
		result = 37 * result
				+ (getLastseen() == null ? 0 : this.getLastseen().hashCode());
		return result;
	}

}
