package it.i_node.tempemail.model;
// Generated 7-mar-2014 17.20.31 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DbmailDatefieldId generated by hbm2java
 */
@Embeddable
public class DbmailDatefieldId implements java.io.Serializable {

	private Long physmessageId;
	private Date datefield;
	private String sortfield;

	public DbmailDatefieldId() {
	}

	public DbmailDatefieldId(Long physmessageId, Date datefield,
			String sortfield) {
		this.physmessageId = physmessageId;
		this.datefield = datefield;
		this.sortfield = sortfield;
	}

	@Column(name = "physmessage_id")
	public Long getPhysmessageId() {
		return this.physmessageId;
	}

	public void setPhysmessageId(Long physmessageId) {
		this.physmessageId = physmessageId;
	}

	@Column(name = "datefield", length = 29)
	public Date getDatefield() {
		return this.datefield;
	}

	public void setDatefield(Date datefield) {
		this.datefield = datefield;
	}

	@Column(name = "sortfield")
	public String getSortfield() {
		return this.sortfield;
	}

	public void setSortfield(String sortfield) {
		this.sortfield = sortfield;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbmailDatefieldId))
			return false;
		DbmailDatefieldId castOther = (DbmailDatefieldId) other;

		return ((this.getPhysmessageId() == castOther.getPhysmessageId()) || (this
				.getPhysmessageId() != null
				&& castOther.getPhysmessageId() != null && this
				.getPhysmessageId().equals(castOther.getPhysmessageId())))
				&& ((this.getDatefield() == castOther.getDatefield()) || (this
						.getDatefield() != null
						&& castOther.getDatefield() != null && this
						.getDatefield().equals(castOther.getDatefield())))
				&& ((this.getSortfield() == castOther.getSortfield()) || (this
						.getSortfield() != null
						&& castOther.getSortfield() != null && this
						.getSortfield().equals(castOther.getSortfield())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPhysmessageId() == null ? 0 : this.getPhysmessageId()
						.hashCode());
		result = 37 * result
				+ (getDatefield() == null ? 0 : this.getDatefield().hashCode());
		result = 37 * result
				+ (getSortfield() == null ? 0 : this.getSortfield().hashCode());
		return result;
	}

}
